### ISSUE TITLE
Completion gets distorted when output is larger than window size

### ISSUE THREAD

**Issue by TLINDEN** [fi-ts/cloudctl#188]
In a proper sized terminal window the output of (e.g.) `cloudctl ip <tab>` looks like this:
```
% c ip 
allocate  (allocate a static IP address for your project that can be used for your cluster's service type load balancer)
delete    (delete an ip)
list      (list ips)
static    (make an ephemeral ip static such that it won't be deleted if not used anymore)
```

However, if the window does not fit the text lines without breaking anymore (that is, if one increases font size or decreases the window size) then the output of `cloudctl ip <tab>` looks like this:
```
% c ip 
$allocate  (allocate a static IP address for your project that can be used for your cluster\s
service
type342200246) delete\ \ \ \ \(delete\ an\ ip\) list\ \ \ \ \ \ \(list\ ips\) static\ \ \ \ \(make\ an\ ephemeral\ ip\ static\ such\ that\ it\ won\t be deleted if not used anymore)
```

The behavior is the same with all completions which contain help texts.

So it seems `cloudctl` is aware of the window size and tries to adapt somehow, but this fails. I'd suggest not to adapt at all.

Env:
```
bash 5.1.4(1)-release

% c version 
client: v0.10.19 (72d20d71), tags/v0.10.19-0-g72d20d7, 2022-06-21T07:45:10Z, go1.18.3
server:
    builddate: "2022-06-20T13:47:20Z"
    gitsha1: 4897315c
    name: cloud-api
    revision: tags/v0.18.23-0-g4897315
    version: v0.18.23
```
