### ISSUE TITLE
Converting an ip address to type static loses existing tags

### ISSUE THREAD

**Issue by mreiger** [fi-ts/cloudctl#37]
Problem
------------

When converting an existing ephemeral ip address to type static with `cloudctl ip static` any existing tags are lost.
Also: Re-creating the tags with cloudctl is not possible; it is necessary to use metalctl wich is not available to customers.

Expected behaviour
---------------------------

Tags are preserved when converting an ephemeral IP to static.

Example
------------

Ephemeral IP address before converting:
```
cloudctl ip list --ipaddress <ipaddress> -o yaml
- changed: <date>
  created: <date>
  description: ""
  ipaddress: <ipaddress>
  name: metallb-<id>
  networkid: internet
  projectid: <project>
  tags:
    - cluster.metal-stack.io/id/namespace/service=<cluster-id>/kube-system/ingress-service
  type: ephemeral
```
After `cloudctl ip static <ipaddress> --name=metallb-<id> --description=""`:
```
cloudctl ip list --ipaddress <ipaddress> -o yaml
- changed: <date>
  created: <date>
  description: ""
  ipaddress: <ipaddress>
  name: metallb-<id>
  networkid: internet
  projectid: <project>
  tags: []
  type: static
```
