### ISSUE TITLE
provide declarative way for cluster managmenet

### ISSUE THREAD

**Issue by mwennrich** [fi-ts/cloudctl#46]
Provide a way to manage cluster in a declarative way with json or yaml, e.g. something like:

```yaml
ID: 7b89f1a2-07c7-40c3-801b-32dc3e938e67
Kubernetes:
  AllowPrivilegedContainers: false
  ExpirationDate:
  Version: '1.17.14'
Labels: {}
Maintenance:
  AutoUpdate:
    KubernetesVersion: false
    MachineImage: false
  TimeWindow:
    Begin: 220000+0100
    End: 233000+0100
Purpose: evaluation
Workers:
  - Name: group-0
    CRI: docker
    MachineImage:
      Name: ubuntu
      Version: '19.10'
    MachineType: c1-xlarge-x86
    MaxSurge: '1'
    MaxUnavailable: '0'
    Maximum: 3
    Minimum: 2
EgressRules:
  - NetworkID: internet
    IPs:
      - 8.9.20.30
FirewallImage: firewall-ubuntu-2.0.20201126
FirewallSize: c1-xlarge-x86
AdditionalNetworks: []
```
